### ISSUE TITLE
since 24.6.21 mobile alerts doesn`t work anymore

### ISSUE THREAD

**Issue by Hombroker** [bluerai/ioBroker.mobile-alerts#17]
API was changed by Mobile Alerts - no data from server anymore.
Adapter needs to be updated by developper.
For RaspberryMatic with ioBroker: Update cannot be loaded manually. Nees to be done via GUI.

**Comment by bluerai** [comment]
1. Have you installed the latest version? If needed please re-install from github.

2. Technically we do not use the API (as it does no support all sensors). We use the "Sensor's Overview"-Page. 
Please try to call the Adapter's webpage from iobroker's instance page. Do you get this page?  If not you have a configuration problem.

3. I cannot say anything about RaspberryMatic with ioBroker because I do not use it.

4. I do not have any current issues with the adapter.

**Comment by Hombroker** [comment]
Hi,

 

unfortunately I cannot update manually with Rasperrymatic and ioBroker as you described.

Other adapter updates are normally listed with its new version number in a separate section of ioBroker which then allows to update this specific one within ioBroker automatically. This works fine for Rapsberymatic -ioBroker.

Can you modify MobileAlert so that updates work as described or list  the new version which I then can install/deinstall? I have still got version 0.0.1.

 

Thanks

 

Von: bluerai ***@***.***> 
Gesendet: Freitag, 2. Juli 2021 11:40
An: bluerai/ioBroker.mobile-alerts ***@***.***>
Cc: Hombroker ***@***.***>; Author ***@***.***>
Betreff: Re: [bluerai/ioBroker.mobile-alerts] since 24.6.21 mobile alerts doesn`t work anymore (#17)

 

1.	Have you installed the latest version? If needed please re-install from github.
2.	Technically we do not use the API (as it does no support all sensors). We use the "Sensor's Overview"-Page.
Please try to call the Adapter's webpage from iobroker's instance page. Do you get this page? If not you have a configuration problem.
3.	I cannot say anything about RaspberryMatic with ioBroker because I do not use it.
4.	I do not have any current issues with the adapter.

**Comment by bluerai** [comment]
This adapter is served "As is". I cannot say anything about RaspberryMatic with ioBroker because I do not use it.

This adapter is not really integrated in the iobroker enviroment - so there is no update by GUI. I was thinking of solving this issue. But today I have noticed that the Mobile Alerts API is supporting many more sensors. Therefore it would be better to use the API and not the Sensor-Overview-Page. 
Sorry, currently I do not have the ressources to do this new development. Maybe someone else can be found for this job.

**Comment by Hombroker** [comment]
It works again with new version 0.51.
I had to manually deinstall old version and then reinstall new version.

**Comment by Hombroker** [comment]
Thanks, works again. See my comment under github. Case can be closed.

 

Von: bluerai ***@***.***> 
Gesendet: Samstag, 3. Juli 2021 12:01
An: bluerai/ioBroker.mobile-alerts ***@***.***>
Cc: Hombroker ***@***.***>; Author ***@***.***>
Betreff: Re: [bluerai/ioBroker.mobile-alerts] since 24.6.21 mobile alerts doesn`t work anymore (#17)

 

This adapter is served "As is". I cannot say anything about RaspberryMatic with ioBroker because I do not use it.

This adapter is not really integrated in the iobroker enviroment - so there is no update by GUI. I was thinking of solving this issue. But today I have noticed that the Mobile Alerts API is supporting many more sensors. Therefore it would be better to use the API and not the Sensor-Overview-Page.
Sorry, currently I do not have the ressources to do this new development. Maybe someone else can be found for this job.
